#Yaml config file

name: ResNet1
data:
        - F:/andrea/AIdataXRF/giulia_weighted_1024_with_labels.h5
        - F:/andrea/AIdataXRF/rescaled12_giulia_weighted_1024_with_labels.h5
        - F:/andrea/AIdataXRF/rescaled22_giulia_weighted_1024_with_labels.h5
        - F:/andrea/AIdataXRF/rescaled23_giulia_weighted_1024_with_labels.h5
        - F:/andrea/AIdataXRF/rescaled33_giulia_weighted_1024_with_labels.h5
        - F:/andrea/AIdataXRF/rescaled44_giulia_weighted_1024_with_labels.h5
        - F:/andrea/AIdataXRF/henryVIII_weighted_1024_with_labels.h5
        - F:/andrea/AIdataXRF/henryVII_2156_weighted_1024_with_labels.h5
        - F:/andrea/AIdataXRF/margaret_weighted_1024_with_labels.h5
        - F:/andrea/AIdataXRF/elisabeth_weighted_1024_with_labels.h5

eval_data:
  - F:/andrea/AIdataXRF/downsample6_giulia_weighted_1024_with_labels.h5
  - F:/andrea/AIdataXRF/downsample6_elgreco_weighted_1024_with_labels.h5
  - F:/andrea/AIdataXRF/downsample9_henryVII_x1024_with_labels.h5

num_threads: 8
device: cuda

model: ResNet1
loss: MSELoss
optimizer: Adam
learning_rate: 0.0005
momentum: 0.0
batch_size: 128
n_epochs: 128

weights: True

channels: 8
